<?php if (isset($exception)): ?>
    <input id="error_system" type="hidden" value="1"/>
    <ul style="list-style: none;margin: 0;padding: 0">
        <li id="errors_message" class="alert alert-error" style='margin-top:10px'">
            <button type="button" class="close" data-dismiss="alert">&times;</button>
            <?php echo "<strong>Erro no sistema:</strong> " . $exception->getMessage(); ?>
        </li>
        <li id="errors_exception" style="display: none">
            <?php echo " in file " . $exception->getFile() . ":" . $exception->getLine(); ?>
        </li>
        <li style="display: none">
            <?php echo $exception->getTraceAsString(); ?>
        </li>
    </ul>
<?php endif; ?>