<?php
// Generated by ZF2's ./bin/templatemap_generator.php
return array(
    //'error/404'               => __DIR__ . '/view/error/404.phtml',
    'error/errorcustom'       => __DIR__ . '/view/error/errorcustom.phtml',
    'error/errorcustomajax'   => __DIR__ . '/view/error/errorcustomajax.phtml',
    //'error/index'             => __DIR__ . '/view/error/index.phtml',
    'layoutjs/admin-layout'   => __DIR__ . '/view/layoutjs/admin-layout.twig',
    'layoutjs/modal-simple'   => __DIR__ . '/view/layoutjs/modal-simple.twig',
    'layoutjs/navigation'     => __DIR__ . '/view/layoutjs/navigation.twig',
    'layoutjs/toolbar-action' => __DIR__ . '/view/layoutjs/toolbar-action.twig',
);
