<?php

/**
 * Configuration file generated by ZFTool
 * The previous configuration file is stored in application.config.old
 *
 * @see https://github.com/zendframework/ZFTool
 */
return [
    'modules' => [
        'Application',
        'DoctrineModule',
        'DoctrineORMModule',
        'DoctrineDataFixtureModule',
        'ZfcTwig',
        'TwbBundle',
        'AssetManager',
        'RdnRequireJS',
        'JSDataTables',
        'JS',
    ],
    'module_listener_options' => [
        'module_paths' => [
            './module',
            './vendor'
        ],
        'config_glob_paths' => [
            //'config/autoload/{,*.}{global,local}.php',
            __DIR__ . '/autoload/doctrine.test.php',
            __DIR__ . '/autoload/global.php',
            __DIR__ . '/autoload/js.global.php',
            __DIR__ . '/autoload/local.php',
        ]
    ],
];
